### ISSUE TITLE
event APIが使用できない

### ISSUE THREAD

**Issue by tatsu1225** [SeeedJP/Wio_Link#1]
Groveコネクタに Button や GenericDigitalInput を設定した時に使用できるevent APIが使用できない

websocketで繋ぐ　wss://us.wio.seeed.io/v1/node/event　が使用できない．
View APIのページより，該当APIの項目からTestRequest(CONNECTボタンを押す)をしても，接続が始まらない．すぐにDISCONNECTされる．

**Comment by matsujirushi** [comment]
サーバー内部でエラーが発生している。

```
[I 220219 05:09:18 handlers:942] websocket open
[E 220219 05:09:19 websocket:496] Uncaught exception in /v1/node/event
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/websocket.py", line 494, in _run_callback
        result = callback(*args, **kwargs)
      File "/home/azureuser/Wio_Link/handlers.py", line 979, in on_message
        self.cur_conn = self.find_node_conn(message.strip())
      File "/home/azureuser/Wio_Link/handlers.py", line 959, in find_node_conn
        for sn, c in self.conns.iteritems():
    AttributeError: 'dict' object has no attribute 'iteritems'
[I 220219 05:09:19 handlers:947] websocket close
```
