### ISSUE TITLE
TypeError: can't concat str to bytearray

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/Wio_Link#3]
サーバーのログに、エラーが記録されている。

```
[E 220204 23:29:10 concurrent:343] Future <tornado.concurrent.Future object at 0x7f2ba4e7e730> exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/azureuser/Wio_Link/server.py", line 355, in start_serving
        ret = yield self.wait_hello()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "/home/azureuser/Wio_Link/server.py", line 160, in wait_hello
        self.stream.write("sorry\r\n")
      File "/usr/local/lib/python3.8/dist-packages/tornado/iostream.py", line 395, in write
        self._write_buffer += data
    TypeError: can't concat str to bytearray
```

**Comment by matsujirushi** [comment]
2022/2/14 23:00 - 2022/2/19 6:00の間に、239件。
