### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 4: invalid continuation byte

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/Wio_Link#7]
サーバーのログに、エラーが記録されている。

```
[E 220219 01:42:21 concurrent:343] Future <tornado.concurrent.Future object at 0x7fce7cc587c0> exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/azureuser/Wio_Link/server.py", line 355, in start_serving
        ret = yield self.wait_hello()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "/home/azureuser/Wio_Link/server.py", line 146, in wait_hello
        sn = str1[0:32].decode()
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 4: invalid continuation byte
```

**Comment by matsujirushi** [comment]
2022/2/14 23:00 - 2022/2/19 6:00の間に、25件。

**Comment by matsujirushi** [comment]
Wio Nodeのファームウェアバージョンが古いときしか実行しない箇所。
https://github.com/SeeedJP/Wio_Link/blob/1578ba6d6f7fe34a397638b95c6015bb2f64689a/server.py#L146

**Comment by matsujirushi** [comment]
[#7.xlsx](https://github.com/SeeedJP/Wio_Link/files/8159705/7.xlsx)
