### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 4: invalid start byte

### ISSUE THREAD

**Issue by matsujirushi** [SeeedJP/Wio_Link#8]
サーバーのログに、エラーが記録されている。

```
[E 220218 20:39:35 concurrent:343] Future <tornado.concurrent.Future object at 0x7fce7d5bfbb0> exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1063, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/azureuser/Wio_Link/server.py", line 355, in start_serving
        ret = yield self.wait_hello()
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/usr/local/lib/python3.8/dist-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 1069, in run
        yielded = self.gen.send(value)
      File "/home/azureuser/Wio_Link/server.py", line 146, in wait_hello
        sn = str1[0:32].decode()
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 4: invalid start byte
```

**Comment by matsujirushi** [comment]
2022/2/14 23:00 - 2022/2/19 6:00の間に、34件。

**Comment by matsujirushi** [comment]
#7 で対処する。
